# CONFIG_ZMK_MOUSE=y
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG_BUFFER_SIZE=65536
CONFIG_ZMK_EXT_POWER=n

# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=0
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
# CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=10
# CONFIG_ZMK_RGB_UNDERGLOW_SAT_STEP=10
# CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=10
# CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=47
# CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=70
# CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=100
# CONFIG_ZMK_RGB_UNDERGLOW_SPD_START=3
# CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0

# Values for CONFIG_ZMK_RGB_UNDERGLOW_EFF_START:
# Value	Effect
# 0	Solid color
# 1	Breathe
# 2	Spectrum
# 3	Swirl


# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
# CONFIG_ZMK_WIDGET_WPM_STATUS=n
